# .github/workflows/docker_build_push.yml
name: Docker Build and Push

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  docker_build_push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add your Docker build and push steps here
