# .github/workflows/github_cli.yml
name: GitHub CLI

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  github_cli:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Set up GitHub CLI
        run: |
          python -m pip install --upgrade gh
      - name: Run GitHub CLI command
        run: gh <your-github-cli-command-here>
