# .github/workflows/labeler.yml
name: Labeler

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  labeler:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run Labeler
        uses: actions/labeler@v4
