# .github/workflows/notify.yml
name: Slack Notification

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Notify on Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON_EMOJI: ":rocket:"
          SLACK_USERNAME: "GitHub Actions"
        with:
          args: 'Workflow ${{ github.workflow }} for ${{ github.repository }} - ${{ github.sha }}'
